title: Yunah Jang
logo: /assets/img/my_pic.png
description: Ph.D. Candidate at SNU
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github_username: YunahJang
linkedin_username: Yunah Jang
google_scholar_id: _9fFSdUAAAAJ
cv_url: /assets/cv/CV_form_2026_yunahjang.pdf